### PR TITLE
Fix for bmlt_changes, function should not be declared static

### PR DESCRIPTION
**Pull request by pjaudiomv**
the bmlt_changes shortcode hasn't worked as long as ive been using bmlt, this fixes it. 
https://bmlt.app/satellites/cms-plugins/shortcodes/#bmlt-changes

**working examples**

[WordPress](https://sca.charlestonna.org/changesword/)
[BMLT Basic](https://nnerna.charlestonna.org/bmlt-basic/changes.php)
[Drupal](https://bmlt-drupal.charlestonna.org/node/4)

### CODE REVIEW

**Review by jbraswell — COMMENTED** [review]
Where are the usages of this function? What was broken?

All I’m not sure this warrants a bump to the major version number. Maybe 3.9.10 would be more appropriate.

**Comment by pjaudiomv** [comment]
Yea I wasn't sure about the version bump. Cool. This function was done not used for the bmlt_changes short code. The whole short code was broken as other function as part of this shortcode couldn't access it as it was static.

**Comment by pjaudiomv** [comment]
this was error i was getting
```
Deprecated: Non-static method BMLTPlugin::process_text() should not be called statically in /home/charl767/nnerna/bmlt-basic/bmlt-basic/vendor/bmlt/bmlt-satellite-base-class/bmlt-cms-satellite-plugin.php on line 2826

Fatal error: Uncaught Error: Using $this when not in object context in /home/charl767/nnerna/bmlt-basic/bmlt-basic/vendor/bmlt/bmlt-satellite-base-class/bmlt-cms-satellite-plugin.php:2826 
Stack trace: #0 /home/charl767/nnerna/bmlt-basic/bmlt-basic/vendor/bmlt/bmlt-satellite-base-class/bmlt-cms-satellite-plugin.php(2803): BMLTPlugin::setup_one_change(Array, NULL) 
#1 /home/charl767/nnerna/bmlt-basic/bmlt-basic/vendor/bmlt/bmlt-satellite-base-class/bmlt-cms-satellite-plugin.php(1821): BMLTPlugin->display_changes('[[bmlt_changes(...') 
#2 /home/charl767/nnerna/bmlt-basic/bmlt-basic/bmlt_basic.class.php(71): BMLTPlugin->content_filter('[[bmlt_changes(...') 
#3 /home/charl767/nnerna/bmlt-basic/changes.php(77): bmlt_basic->output_body() 
#4 {main} thrown in /home/charl767/nnerna/bmlt-basic/bmlt-basic/vendor/bmlt/bmlt-satellite-base-class/bmlt-cms-satellite-plugin.php on line 2826
```

**Comment by ghost** [comment]
Looks like a “my bad”. I wrote most of this code before I saw The Light about unit testing, so there’s probably a number of untrodden code paths.

One of the annoying things about loosely-typed scripting languages, is that you will often encounter stuff like this ages after causing the bug.

Thanks.

**Comment by jbraswell** [comment]
I want to be sure there aren’t any usages out there that use it as an actual static method. This is a library used by multiple other products that could call this method isn’t it?

**Comment by LittleGreenViper** [comment]
Ugh. That was annoying.
I logged in with the wrong ID.
I suspect it’s not being used elsewhere, as this looks like an error that would pop up if the path was executed.

**Comment by LittleGreenViper** [comment]
I think the people that might use this are NAMN. Might want to check with Jeff Spencer, but they tend to use existing code; not write their own.

**Comment by pjaudiomv** [comment]
yea its not, only being used as a part of that shortcode. and is only called once here
https://github.com/bmlt-enabled/bmlt-satellite-base-class/blob/7d360470bb7fbe2e0a9c60f1b57ee2f1a0515a4b/bmlt-cms-satellite-plugin.php#L2801-L2804

should that then be called with the object operator `$this->` ?

**Comment by pjaudiomv** [comment]
you can check out the unit test for bmlt_changes here
https://nerna.org/wp-content/plugins/bmlt-wordpress-satellite-plugin/vendor/bmlt/bmlt-satellite-base-class/unit_test.php

**Comment by pjaudiomv** [comment]
more specifically here
https://nerna.org/wp-content/plugins/bmlt-wordpress-satellite-plugin/vendor/bmlt/bmlt-satellite-base-class/unit_test.php?utest_string=[[bmlt_changes(switcher%3DGetChanges%26start_date%3D2018-09-19)]]&mobile_simulation=

and working unit test with change here
https://sca.charlestonna.org/wp-content/plugins/bmlt-wordpress-satellite-plugin/vendor/bmlt/bmlt-satellite-base-class/unit_test.php?utest_string=%5B%5Bbmlt_changes%28switcher%3DGetChanges%26start_date%3D2018-09-19%29%5D%5D&mobile_simulation=

**Comment by pjaudiomv** [comment]
I firmly believe this is the right way to do this. I have researched the code base and and have tested. function should not be static, should also be called with object operator.

**Review by jbraswell — APPROVED** [review]

**Comment by jbraswell** [comment]
Merge it brah

**Comment by pjaudiomv** [comment]
squash

**Pull request merged**
