### PR TITLE
Only define ROOTPATH if not defined already

### PR DESCRIPTION
**Pull request by pjaudiomv**
this will fix the ROOTPATH already defined warnings.

### CODE REVIEW

**Comment by dgershman** [comment]
I think the change needs to be in the driver too.

**Comment by dgershman** [comment]
Go ahead and release this, if you feel confident that it will solve issues.

**Comment by pjaudiomv** [comment]
ok cool the driver actually doesnt need to be updated i dont think. It doesnt care where it is. i grepped it and theres no instanse of DIR or ROOTPATH or any paths really.

**Comment by dgershman** [comment]
Right the plugin does though.

**Pull request merged**
